apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infrastructure-interview-test-main.fullname" . }}
type: Opaque
data:
  TYPEORM_PASSWORD: {{ .Values.TYPEORM_PASSWORD | default (randAlphaNum 32) | b64enc | quote }}